# Generated by Django 3.0.7 on 2020-06-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter Job Name', max_length=70, null=True)),
                ('description', models.TextField(help_text='Enter Job Description', max_length=1000, null=True)),
                ('job_type', models.CharField(choices=[('P', 'Part Time'), ('F', 'Full Time')], max_length=1)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
